### PR TITLE
Tech 650 sensu alerts

### PR DESCRIPTION
**Pull request by deltaroe**
@sherriman @Inanepenguin

[Review on Reviewable](https://reviewable.io/reviews/invoca/exception_handling/6)

### CODE REVIEW

**Comment by sherriman** [comment]
Reviewed 1 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[lib/exception_handling.rb, line 312 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0UVwldRS-O3X8Fbt)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L312)):</sup>
Should this method just do the sensu part, and leave the log_error up to the caller?  It doesn't seem by the name that it does both.

---

<sup>**[lib/exception_handling.rb, line 317 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0Qovpdpufwlqo8BZ)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L317)):</sup>
You are shadowing ex, that is confusing.  Pick a new name.

---

<sup>**[lib/exception_handling.rb, line 318 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0dffLlrJTxd3vAQM)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L318)):</sup>
I would add some context here, like `log_error(ex, 'ExceptionHandling.ensu_warning' )`

---

<sup>**[lib/exception_handling.rb, line 322 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0wTFIlrNf_Pw-yNV)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L322)):</sup>
I think this should take an exception_context, like ensure_safe.

In that case, would we send the ensure_safe or the exception message to Sensu?  I am leaning towards the exception_context because it would be consistent, but the exception message might be more actionable.

---

<sup>**[lib/exception_handling/sensu.rb, line 4 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0DK-pDyGWY1jGHv3)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L4)):</sup>
Module would be more "honest" since we don't have any instance methods.

---

<sup>**[lib/exception_handling/sensu.rb, line 7 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-LB3bYc64GF7IZMH)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L7)):</sup>
Can we make this a hash LEVELS = {}

status = LEVELS[level] or rase "Invalid alert level #{level}"

---

<sup>**[lib/exception_handling/sensu.rb, line 13 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-YT2CmLuDFozCS4X)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L13)):</sup>
to_s is not needed #{} does that for you.

---

<sup>**[lib/exception_handling/sensu.rb, line 16 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0-OO8-no-z5D_Uqy)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L16)):</sup>
`"#{ExceptionHandling.sensu_prefix}#{name}"`
could be the following, you don't need string interpolation.
`ExceptionHandling.sensu_prefix + name`

---

<sup>**[lib/exception_handling/sensu.rb, line 25 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-h5HBR9TjdbUZCif)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L25)):</sup>
What if s is nil because new raised?  I think you want to a little bit different block structure.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling.rb, line 312 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0UVwldRS-O3X8Fbt)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L312)):</sup>
I was basing the naming off what was used for the escalation related functions. This function in particular I based off of https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L297

I'd like to keep the naming consistent if possible so if we want to change the name of this function I think we should change the escalation function naming as well

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling.rb, line 317 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0Qovpdpufwlqo8BZ)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L317)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling.rb, line 318 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0dffLlrJTxd3vAQM)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L318)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 4 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0DK-pDyGWY1jGHv3)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L4)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 13 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-YT2CmLuDFozCS4X)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L13)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 16 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0-OO8-no-z5D_Uqy)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L16)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 25 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-h5HBR9TjdbUZCif)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L25)):</sup>
thinking about this again any issues with the socket are going to be because it never opened or closed unexpectedly making putting the close inside an ensure block useless. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 7 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-LB3bYc64GF7IZMH)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L7)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling.rb, line 322 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0wTFIlrNf_Pw-yNV)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L322)):</sup>
I have a few questions I want to ask you about this when you have tme

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by sherriman** [comment]
Reviewed 3 of 6 files at r1.
Review status: 1 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[lib/exception_handling/sensu.rb, line 22 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-h5HBR9TjdbUZCif)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L22)):</sup>
Do we even need to close s?  The GC should take care of it, right?

Even better, what about trying `Socket.tcp` http://ruby-doc.org/stdlib-1.9.3/libdoc/socket/rdoc/Socket.html#method-c-tcp

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by sherriman** [comment]
Comments given.  I think there is just some open questions from you about my comments you want to discuss in person.

---

Reviewed 1 of 6 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[lib/exception_handling.rb, line 322 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0wTFIlrNf_Pw-yNV)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L322)):</sup>
Happy to discuss Monday afternoon.

---

<sup>**[lib/exception_handling/sensu.rb, line 14 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA3CtF1oP2NLYSsLM9)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/lib/exception_handling/sensu.rb#L14)):</sup>
sensu_prefix can be nil, so in the case case you need ExceptionHandling.sensu_prefix.to_s

---

<sup>**[test/test_helper.rb, line 38 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA1rdzmRoYdga_lnKz)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/test/test_helper.rb#L38)):</sup>
See Ben, he is trying to prevent adding more here.  I think we want this in its own file?  Ben can say what process he is using to split things out.

---

<sup>**[test/unit/exception_handling/sensu_test.rb, line 29 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA2cdjUFgztSrGSk07)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/test/unit/exception_handling/sensu_test.rb#L29)):</sup>
You should check the error message too.  I think that the second argument of `assert_raise` takes the message to check.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by sherriman** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[lib/exception_handling.rb, line 322 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0wTFIlrNf_Pw-yNV)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L322)):</sup>
`ensure_alert( alert_name, exception_context`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 14 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA3CtF1oP2NLYSsLM9)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/lib/exception_handling/sensu.rb#L14)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[lib/exception_handling/sensu.rb, line 25 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl-h5HBR9TjdbUZCif)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling/sensu.rb#L25)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[test/test_helper.rb, line 38 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA1rdzmRoYdga_lnKz)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/test/test_helper.rb#L38)):</sup>
The is not the web repo, do you still want me to split it out?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
<sup>**[test/unit/exception_handling/sensu_test.rb, line 29 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA2cdjUFgztSrGSk07)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/test/unit/exception_handling/sensu_test.rb#L29)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
I think that's everything. Please take a quick look back over this and let me know if there's something else


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by deltaroe** [comment]
Review status: 1 of 6 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[lib/exception_handling.rb, line 322 \[r1\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-Jxl0wTFIlrNf_Pw-yNV)** ([raw file](https://github.com/invoca/exception_handling/blob/d79ae34658458c3c11cfdbd55a1b64e3e49db537/lib/exception_handling.rb#L322)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by sherriman** [comment]
<sup>**[test/test_helper.rb, line 38 \[r2\]](https://reviewable.io:443/reviews/invoca/exception_handling/6#-JzA1rdzmRoYdga_lnKz)** ([raw file](https://github.com/invoca/exception_handling/blob/1a12a1b51b6df24c96d0458370e2c4ab0d5ba366/test/test_helper.rb#L38)):</sup>
No we don't need to split it out.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Comment by sherriman** [comment]
Looks great.  I like how `Socket.tcp` works.  Clean and removed the test cases :)

Given that this is a Gem, I am not certain what the next steps are to get it QAed, plus the versioning of it within web branches.  So please run with a plan on that.


---

Reviewed 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/invoca/exception_handling/6)

**Pull request merged**
