### PR TITLE
Tech 7218 remove honeybadger fork

### PR DESCRIPTION
**Pull request by robertp**
Swap out our Honeybadger fork for the official gem. Remove the callback that prints ids/keys of PORO/AR ruby objects.

### CODE REVIEW

**Comment by robertp** [comment]
Note that we want to release a -pre version from the feature branch before merging to main/master.

**Review by ColinDKelley — APPROVED** [review]
Looks good!

**Review by gwynethallwright — APPROVED** [review]

**Review by yinonrousso — APPROVED** [review]
Looks like a really clean upgrade 👍 
Is `exception_handling` the only direct consumer of the honeybadger gem? 🎉

**Comment by robertp** [comment]
> Looks like a really clean upgrade 👍 Is `exception_handling` the only direct consumer of the honeybadger gem? 🎉

I haven't checked all the repos but I think it *should* be.

**Pull request merged**
